modLoader="javafml" #mandatory
loaderVersion="[39,)"
license="All rights reserved"

[[mods]] #mandatory
modId="graveyard_biomes" #mandatory
version="1.4" #mandatory
displayName="The Graveyard Biomes" #mandatory

logoFile="graveyard_logo.png"
credits="" #optional
authors="Finallion"
description='''
The Graveyard Biomes adds new spooky biomes - an independent extension to the Graveyard (FORGE) mod.
'''

[[dependencies.graveyard_biomes]]
    modId="forge"
    mandatory=true
    versionRange="[44.0.3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.graveyard_biomes]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3]"
    ordering="NONE"
    side="BOTH"
[[dependencies.graveyard_biomes]]
    modId = "terrablender"
    mandatory = true
    versionRange = "[1-19.3-2.1.0.134,)"
    ordering = "NONE"
    side = "BOTH"
